language: python

python:
  - 2.7
  - 3.5

notifications:
  email:
    recipients:
      - gallardolin@gmail.com
    on_success: always
    on_failure: always

# command to install dependencies
install:
  - "pip install -r test-requirements.txt"

script: 
  - python setup.py nosetests --tests test/unit_test
  - flake8
