
variables:
  GIT_SSL_NO_VERIFY: "1"

before_script:
  - python --version
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

py2.7:
  tags:
  - python-2.7
  script:
  - python setup.py nosetests --tests tests/unit
  - flake8

py3.5:
  tags:
  - python-3.5
  script:
  - python setup.py nosetests --tests tests/unit
  - flake8
