language: python

python:
  - 2.7
  - 3.5

notifications:
  email:
    recipients:
      - gallardolin@gmail.com
    on_success: always
    on_failure: always

script: 
  - python setup.py nosetests --tests tests/unit
  - flake8
